### ISSUE TITLE
 have to enable the validation mode on the SDK?

### ISSUE THREAD

**Issue by superdiazzz** [teads/TeadsSDK-android#139]
Based on this website [https://support.teads.tv/support/solutions/articles/36000166954-5-validate-your-integration-beta-](url) to use validation mode, i have to enable validation mode on SDK but i don't know how to do it? Can somebody explain to me how?

**Comment by HugoGresse** [comment]
Hi,
Sorry for the issue, we've updated the documentation to fix this. 
Here is also the needed part to enable it: 
```
mInReadAdView.load(new AdSettings.Builder()
    .enableValidationMode()
    .build());
```

**Comment by superdiazzz** [comment]
I have encounter new issue after added attribute inside load ads(enableValidationMode), there was no popup then stacktrace like below

> E/EventBus: Could not dispatch event: class tv.teads.sdk.android.engine.web.event.OpenDialogRequest to subscribing class class tv.teads.sdk.android.engine.ui.UIEngine
>     android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
>         at android.view.ViewRootImpl.setView(ViewRootImpl.java:765)
>         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
>         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
>         at android.app.Dialog.show(Dialog.java:330)
>         at tv.teads.sdk.android.utils.DialogUtils.a(DialogUtils.java:65)
>         at tv.teads.sdk.android.engine.ui.UIEngine.onEvent(UIEngine.java:325)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
>         at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
>         at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
>         at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
>         at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
>         at tv.teads.sdk.android.engine.web.WebEngine.a(WebEngine.java:407)
>         at tv.teads.sdk.android.engine.web.commander.webview.WebViewBridge.openDialog(WebViewBridge.java:518)
>         at tv.teads.sdk.android.engine.web.commander.webview.Commander.openDialog(Commander.java:368)
>         at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
>         at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by HugoGresse** [comment]
hmm, that's weird. Do you think you can isolate the issue in a new app, following #140 ?

**Comment by adlibsv** [comment]
Hi!
Even if the validation tool is enabled, the popup does not appear to me. 
   ```
      requestSettings = AdRequestSettings.Builder()
                    .pageSlotUrl("http://teads.com")
                    .enableValidationMode()
                    .build()
```
Did not noticed any exception in the logs or any clue why the validation popup doesn't appear. Any tips/idea?
Thanks!

**Comment by github-maxime-liege** [comment]
Hi @adlibsv,

Can you give us more context about your integration type ?
- Are you using mediation or direct teads ?
- Your SDK version
- Some logs when Teads is being called

Thank you for your feedback !

**Comment by adlibsv** [comment]
Hi!
Here are the answers to the questions above:
- direct standard integration
- v5.0.12
- 2022-04-07 09:56:16.548 D/teads#AssetUpdater: lib-js up to date
2022-04-07 09:56:16.733 D/teads#PerfTeads: p23: 1063
2022-04-07 09:56:16.780 D/teads#AdPlacement: Init advertising ids and adLoader...
2022-04-07 09:56:16.781 D/teads#AdPlacement: Init - Advertising ids OK
2022-04-07 09:56:16.783 D/teads#InReadAdPlacement: Waiting placement to be ready for ad request
2022-04-07 09:56:16.784 D/teads#PerfTeads: p10: 5
2022-04-07 09:56:16.784 D/teads#AdPlacement: Init - AdLoader asset recovered
2022-04-07 09:56:16.806 D/teads#PerfTeads: p11: 27
2022-04-07 09:56:16.806 D/teads#AdPlacement: Init - AdLoader OK
2022-04-07 09:56:16.807 D/teads#InReadAdPlacement: Request InRead Ad
2022-04-07 09:56:16.807 D/teads#JsEngine: ---->AdLoaderModule.requestInReadAd(84242, '%7B%22debugModeEnabled%22%3Atrue%2C%22locationEnabled%22%3Afalse%2C%22lightEndScreenEnabled%22%3Afalse%2C%22consent%22%3A%22%22%2C%22subjectToGDPR%22%3A%220%22%2C%22tcfVersion%22%3A2%2C%22cmpSdkID%22%3A0%2C%22crashReporterEnabled%22%3Atrue%2C%22extras%22%3A%7B%7D%2C%22browserUrlHidden%22%3Afalse%2C%22browserToolbarBackgroundColor%22%3A0%7D', '%7B%22publisherSlotUrl%22%3A%22http%3A%2F%2Fteads.com%22%2C%22validationModeEnabled%22%3Afalse%2C%22extras%22%3A%7B%7D%2C%22listenerKey%22%3A-1%7D')
2022-04-07 09:56:16.829 D/teads#LoggerBridge: t:placementCall
2022-04-07 09:56:16.831 D/teads#LoggerBridge: Building usPrivacy string...
2022-04-07 09:56:16.832 D/teads#LoggerBridge: Building referrerUrl string...
2022-04-07 09:56:16.832 D/teads#LoggerBridge: Creating & returns the built AdRequest...
2022-04-07 09:56:16.848 D/teads#LoggerBridge: Creating url & body request
2022-04-07 09:56:16.848 D/teads#LoggerBridge: Post the AdRequest
    URL: https://r.teads.tv/rich/84242?responseSerialization=v2
    Body: locale=en_US&country=US&windowReferrerUrl=http%3A%2F%2Fteads.com&userId=081439f9-7ea6-455b-a96d-88f155e5172c&network=wifi&deviceType=samsung%20SM-G991U1&screenHeight=725&screenWidth=360&deviceFamily=smartphone&carrier=&osVersion=31&os=Android&appVersion=12.16&appId=com.pinger.textfree.call&browser=SDK&sdkVersion=5.0.12&env=sdk-inapp&gdprIab=%7B%22status%22%3A21%2C%22consent%22%3Anull%2C%22reason%22%3A210%2C%22apiVersion%22%3Anull%2C%22cmpId%22%3Anull%7D&tag=84242&sdkEngineVersion=66&sdkIntegrationType=classic&apiFrameworks=1%2C2%2C7&omidPn=Teadstv

**Comment by github-maxime-liege** [comment]
Hi @adlibsv<

I can see in logs that the validation mode is not enabled, did you put the setup the settings correctly ?

Can you create another issue to get correct following regarding this ?

Thank you,

**Comment by github-maxime-liege** [comment]
I created an issue with your previous message

**Comment by adlibsv** [comment]
> I can see in logs that the validation mode is not enabled, did you put the setup the settings correctly ?

Really sorry about that - I think we logs pasted here are not correct, I must have been collected them when the validation mode was not enabled. Anyways, noticed that when it is enabled, then the popup does not appear, BUT in the logs there is something like:
```
W/teads#LoggerBridge: To start the validation, open this page on your desktop:
  https://sdkvalidation.teads.tv/1NLp4JuPZ
  Waiting for the first test to start...
```
and when clicking the link it does open in the browser.

**Comment by HugoGresse** [comment]
Do you have an an blocker?
