### ISSUE TITLE
Could not resolve tv.teads.* | Bintray dependencies issue

### ISSUE THREAD

**Issue by HugoGresse** [teads/TeadsSDK-android#144]
As of now, Teads Android SDK & dependencies are not able to be resolved on Teads Bintray account. 
We are working on solving this ASAP and will update this ticket when we have more information / ETA.

**Comment by HugoGresse** [comment]
We've contacted Bintray to understand/resolve the issue and are waiting for an answer (50min ago)

**Comment by HugoGresse** [comment]
We found the issue and are working to resolve this. Should be fixed by EOD

**Comment by vincentsaluzzo** [comment]
The problem is normally fixed right now. Sorry for the inconvenience.
