### ISSUE TITLE
Teads Ads Display just white space

### ISSUE THREAD

**Issue by superdiazzz** [teads/TeadsSDK-android#152]
Hi Teads Team,

i have done test for Teads ads in debug mode, and the result shows as below
![Screen Shot 2020-06-22 at 09 04 41](https://user-images.githubusercontent.com/10770867/85241914-9d2fad00-b467-11ea-9dd3-c7f074b9c9d2.png)

i using dependency 
`implementation('tv.teads.sdk.android:sdk:4.7.2@aar') {
        transitive = true
    }`

and i wrote code like this

```
parentLayout!!.post {
                
                videoAds!!.setPid(Integer.valueOf(activity.getString(R.string.ads_teads)))
                videoAds!!.listener = object : TeadsListener(){

                    override fun onAdFailedToLoad(adFailedReason: AdFailedReason?) {
                        super.onAdFailedToLoad(adFailedReason)

                        val code = adFailedReason?.errorCode
                        if(code == TribunTeadsListener.ERROR_NOTFILLED){
                            // display ADX if only no Filling Rate
                            mPublisherAdViewTop = PublisherAdView(activity).apply {
                                setAdSizes(com.google.android.gms.ads.AdSize.MEDIUM_RECTANGLE)
                                setPadding(0, 12, 0, 12)
                                adUnitId = activity.getString(R.string.ads_TopMediumRectangle)
                                adListener = TribunAdListener(mPublisherAdViewTop)
                            }
                            parentLayout!!.addView(mPublisherAdViewTop)
                        }

                    }

                    override fun onError(s: String?) {
                        super.onError(s)
                        Timber.e("TribunTeadsListener ERROR -- %s", s)
                    }

                    override fun onAdPlaybackChange(state: Int) {
                        super.onAdPlaybackChange(state)
                        when (state) {
                            PlayerConstants.LOADED, PlayerConstants.STARTED, PlayerConstants.RESUMED,
                            PlayerConstants.PAUSED, PlayerConstants.IMPRESSION, PlayerConstants.PROGRESS,
                            PlayerConstants.FIRST_QUARTILE, PlayerConstants.MID_POINT, PlayerConstants.THIRD_QUARTILE,
                            PlayerConstants.COMPLETE, PlayerConstants.STOPPED, PlayerConstants.MUTED, PlayerConstants.UNMUTED -> {
                            }
                            else -> {
                            }
                        }
                    }
                }

                val viewGroup: ViewGroup? = itemView.findViewById<ViewGroup?>(R.id.adContainer)
                videoAds!!.setAdContainerView(viewGroup)
                videoAds!!.load(AdSettings.Builder()
                        .pageUrl(linkNews)
                        .userConsent("0", "0").enableValidationMode()
                        .build())

                }
```
And this is what happened in read implementation
![WhatsApp Image 2020-06-22 at 09 11 26](https://user-images.githubusercontent.com/10770867/85242160-6c03ac80-b468-11ea-80e2-9caf3e41bfa1.jpeg)
 and we error with app-ads.txt, however i have registrated the Teads id in txt file in our website.
![Screen Shot 2020-06-22 at 09 15 53](https://user-images.githubusercontent.com/10770867/85242342-019f3c00-b469-11ea-8d17-f15c0213e10e.png)
you can check if txt file has included with teads here: [app-ads.txt](https://www.tribunnews.com/app-ads.txt)
So how can we solve this problem? it has been over 24 hours since we update http to https website, google crawler should be have done with this. but why it still doesn't work yet?  please help us

**Comment by benjaminvolland** [comment]
Hello @superdiazzz, did you succeed to solve the issue on your side?

**Comment by superdiazzz** [comment]
@benjaminvolland i got report about teads ads display for a momen. I thought the issue has solved, but when i tried to perform sdkvalidation, app-ads.txt still not recognized. Also i can't update the dependency because of this:
![Screen Shot 2020-07-01 at 08 11 33](https://user-images.githubusercontent.com/10770867/86192314-7a8e4a00-bb73-11ea-99fb-4740755178e1.png)
 our minimum sdk is 17

**Comment by benjaminvolland** [comment]
Hello @superdiazzz , yes on [4.7.3](https://github.com/teads/TeadsSDK-android/releases/tag/v4.7.3) we added the Huawei SDK to deliver ads on devices without play services (and with "huawei services"), this feature add a breaking change on the min SDK supported.
The only way to integrate the version [4.7.3](https://github.com/teads/TeadsSDK-android/releases/tag/v4.7.3) is to upgrade your min SDK supported, or to keep an old version (4.7.1). Sorry for the inconvenience.

**Comment by superdiazzz** [comment]
Owh man... we can't upgrade minimum sdk to 19 for some reason. Probably we could keep the old version for this moment. But can you help us to make the old version keep available. However, our app-ads.txt still unrecognized please help 👶

**Comment by HugoGresse** [comment]
just posting there, you can remove a transitivie dependencies from gradle, and also force a [minSdk](https://stackoverflow.com/questions/24494077/gradle-force-build-tools-version-on-third-party-libraries) on  dependencies. 

Remove transitive dep: 
```
dependencies {
  compile ('org.springframework.data:spring-data-hadoop-core:2.0.0.M4-hadoop22') {
    exclude group: "org.slf4j", name: "slf4j-log4j12"
  }
}
```

Anyway, this issue probably need to be closed 😅

**Comment by benjaminvolland** [comment]
Thanks @HugoGresse for the solution. @superdiazzz Does this solve the issue?

**Comment by superdiazzz** [comment]
Hi @HugoGresse , Hi @benjaminvolland  sorry for long response. But i didn't do anything recently and i think there is no issue except filling rate.  Anyways thanks... i will try to implement this and reopen if issue case appears.
