### ISSUE TITLE
Duplicate class a.a.a.a.a.a found in modules jetified-sdk-4.8.1-runtime.jar  (tv.teads.sdk.android:sdk:4.8.1)

### ISSUE THREAD

**Issue by MrBrightside29** [teads/TeadsSDK-android#158]
Hi,

I am unable to compile my project after adding latest Teads dependency and having also Stripe. 
```
Duplicate class a.a.a.a.a.a found in modules jetified-sdk-4.8.1-runtime.jar (tv.teads.sdk.android:sdk:4.8.1) and jetified-stripe-3ds2-android-4.1.2-runtime.jar (com.stripe:stripe-3ds2-android:4.1.2)
Duplicate class a.a.a.a.a.c found in modules jetified-sdk-4.8.1-runtime.jar (tv.teads.sdk.android:sdk:4.8.1) and jetified-stripe-3ds2-android-4.1.2-runtime.jar (com.stripe:stripe-3ds2-android:4.1.2)
Duplicate class a.a.a.a.a.f found in modules jetified-sdk-4.8.1-runtime.jar (tv.teads.sdk.android:sdk:4.8.1) and jetified-stripe-3ds2-android-4.1.2-runtime.jar (com.stripe:stripe-3ds2-android:4.1.2)
```

**Comment by ndahmani** [comment]
Hi @MrBrightside29,
We do work on a fix, we'll update you asap
Bests,

**Comment by ndahmani** [comment]
Hi @MrBrightside29,
We did release a fix, find the latest version [here](https://github.com/teads/TeadsSDK-android/releases/latest)
Please checkout these documentation sections that might help along the way:
- [Test multiple sized creatives](https://support.teads.tv/support/solutions/articles/36000257516-placement-id-for-tests)
- [Troubleshoot common issues](https://support.teads.tv/support/solutions/articles/36000260537-troubleshooting)
- [Validate your integration](https://support.teads.tv/support/solutions/articles/36000209100-validation-tool)
Bests,

**Comment by MrBrightside29** [comment]
Hi @ndahmani, everything is working fine now! Thanks for the fast fix!
