### ISSUE TITLE
Je prends des nouvelles 🤗

### ISSUE THREAD

**Issue by HugoGresse** [teads/TeadsSDK-android#169]
Coucou, alors ça va bien la team SDK ?

**Comment by github-benjamin-volland** [comment]
Hello @HugoGresse !
La team est au top, comme toujours, merci 😃 
Et du côté de PlantNet?

*PS: Profite de ce passage pour tester le nouveau [SDK V5](https://github.com/teads/TeadsSDK-android/releases)* 😉

**Comment by HugoGresse** [comment]
Pl@ntNet ça va aussi ! 
Bon courage pour la fin d'année et pour corriger les bug du v5 du coup ! 😅
