### ISSUE TITLE
Is there custom mediation support?

### ISSUE THREAD

**Issue by yilmazgokhan** [teads/TeadsSDK-android#173]
When we examined the [Teads SDK Documentation](https://support.teads.tv/support/solutions/articles/36000314755), we noticed that there is mediation support for several different advertising networks. We couldn't find any explanation as to whether custom mediation support is available for ad networks not listed. Any idea if this support is available?

**Comment by github-geoffrey-dudragne** [comment]
Hello @yilmazgokhan,

The public documentation only shows the officially supported adapters for mediation (mopub, admob and smart). It is totally possible to integrate with other mediation solutions, but a custom adapter will have to be implemented by the app developer.
We can however provide advice and support to help you with the adapter implementation if you ask further questions. 

In which ad network would you like to integrate the Teads SDK?

**Comment by yilmazgokhan** [comment]
Thanks for your reply @github-geoffrey-dudragne 

I want to use Teads SDK via Huawei Ads. Is there any support about that?

**Comment by github-geoffrey-dudragne** [comment]
We've never worked with Huawei Ads. But it doesn't seem to be a mediation solution. Do you mean integrating both Huawei Ads and Teads SDK within a mediation solution like Admob or Mopub?

**Comment by yilmazgokhan** [comment]
Yes, I want to integrate Huawei Ads through Teads SDK with mediation.

**Comment by github-geoffrey-dudragne** [comment]
I heard from our product manager that Huawei is working on their own mediation. We might add support for it in the future, but for now we are waiting for their solution to be officially released (I haven't found any public documentation about how to integrate their solution as mediation on the Publisher side).
