### ISSUE TITLE
About the equivalent of Teads ad types in other ad networks

### ISSUE THREAD

**Issue by yilmazgokhan** [teads/TeadsSDK-android#174]
When we examined the [Teads SDK Documentation](https://www.teads.com/viewable-outstream-teads-formats/), we noticed that the ad types are different from other ad networks like Google AdMob.

**Google AdMob ad types:**
- Banner
- Interstitial
- Rewarded Interstitial
- Rewarded
- Native
- App open

**Teads ad types:** 
- inRead Video
- inRead Live
- inRead Flow
- inRead Carousel
- inRead Scroller
- inRead Cinemagraph

We are not sure which of these ads has similar features. For example, what is the equivalent of the banner ad type in Google AdMob in the Teads?

**Comment by github-geoffrey-dudragne** [comment]
Hello @yilmazgokhan,

inRead is an ad format that is very common for Teads, it consists of placing the ad inside some articles to provide quality integrations in media articles for example.
Video, Live, Flow, Carousel... are some different creative types for the look and feel and all work in any inRead placement. Examples: https://www.teads.com/viewable-outstream-teads-formats/   

We could simplify by saying inRead is like an AdMob Banner (300x250  IAB Medium Rectangle) but typically within a scrollable view, and with resizable capabilities. There are some examples of integration of Teads with our official AdMob adapter inside this sample app https://github.com/teads/TeadsSDK-android/blob/master/TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/admob/AdMobScrollViewFragment.kt#L46

**Comment by yilmazgokhan** [comment]
Thanks for reply @github-geoffrey-dudragne 

We will clone the repo and try it. If we use inRead type as a AdMob banner via mediation, is there any UI issues, impression issues, revenue issues or another issues?

**Comment by github-geoffrey-dudragne** [comment]
Please refer to our public documentation for information about AdMob inRead integration https://support.teads.tv/support/solutions/articles/36000314743-inread-google-ad-manager-and-admob-mediation
The solution is fully functional for impression and revenues, you can make sure about it by running the validation tool once your integration is complete https://support.teads.tv/support/solutions/articles/36000314753-validation-tool
For proper rendering, the resize listener should be integrated as mediation solutions might constrain the slot size.

**Comment by basakyardim** [comment]
Hello @github-geoffrey-dudragne 
We analyzed the repo you sent. In the app:
1-There is no ad that should come from different ad networks, there are only Teads ads.
2- We could not see a different ad request because only one type of ad was displayed. Also, there is no part where we can see type I (banner, etc.) in the request.
The reason for the one type of ad request is that Teads only support banner in AdMob mediation?

**Comment by github-geoffrey-dudragne** [comment]
1 - This [repo](https://github.com/teads/TeadsSDK-android) we provide is for showing how Teads SDK can be integrated directly, or using mediation solutions. Therefore it doesn't contain any integration with other adNetworks. We aren't a mediation solution today so we can't be integrated directly with other AdNetwork.
2- For mediation we only support inRead and native (https://support.teads.tv/support/solutions/folders/36000235259), which are using admob banner and native ad types. However for the moment this repo only contains Teads SDK AdMob adapter examples for inRead ad.
