### ISSUE TITLE
Jetifier still not removed

### ISSUE THREAD

**Issue by herrbert74** [teads/TeadsSDK-android#175]
This was addressed before, but no properly:
https://github.com/teads/TeadsSDK-android/issues/163

This is still not fixed in 5.0.10.
Not only do you have to change to androidX, but you also have to update your dependencies.
You still depend on picasso:2.71828 from 2018, tv.teads.exoplayer:exoplayer-core:r2.4.3, and tv.teads.visdroid:library:1:10, which in turn depend on the support libraries.
Also, if you remove jetifier from gradle.properties, you should have already seen these warnings, which proves that this issue is actually not fixed.

Excluding the dependencies is not helping as the are needed runtime.

This is a major issue, overdue for two years. The only blocker removing Jetifier in our large app is now Teads SDK. Please fix this ASAP!

**Comment by github-geoffrey-dudragne** [comment]
Hello @herrbert74,

Thanks for drawing our attention to this issue. Indeed we did not fully complete the migration to allow getting rid of Jetifier. 

We are already fixing our dependencies on problematic Picasso and visdroid libraries. We also started working on the update of the exoplayer dependency. However it contains impacting breaking changes so it will not be released immediately, we are planning for a release fixing it during March.

Sorry for the inconvenience

**Comment by herrbert74** [comment]
Understandable, thanks.

**Comment by herrbert74** [comment]
I tried to add 5.0.12, but it's still using ExoPlayer 2.4.3. Am I right that this is the last one? Do we have any ETA?

**Comment by github-geoffrey-dudragne** [comment]
It's not ready yet, we're taking some more time to review the change and to make sure the update for the ExoPlayer won't cause any compatibility issues with apps integrating our SDK. It should be updated in next release.

**Comment by github-geoffrey-dudragne** [comment]
Hello @herrbert74 we have released last week a new SDK version that gets rid of jetifier completely
