### ISSUE TITLE
visibility 0

### ISSUE THREAD

**Issue by ThandarLynn** [teads/TeadsSDK-android#185]
read me
I am trying to add teads in webview.
adCore.notifyAssetsDisplayChanged({"-1":{"visibility":0,"width":392,"height":242},"6":{"visibility":0,"width":391,"height":220}});

visiblity showing 0 in log
Do you have any suggestion?

thank you

**Comment by github-maxime-liege** [comment]
Hello,

We cannot help you with that few information

Can you bring us more information like:
- SDK Version
- Android Version
- Ad type (InRead/Native)
- Is the ad running
- A screenshot would be appreciated


Thank you,

**Comment by ThandarLynn** [comment]
I solved that one.

I want to ask you another one advice.

in your demo code , you are using toolbar in mobile code.
but I am using webview toolbar in my code.

so your teads does not overlap on toolbar.
but my teads is overlapping on webview toolbar.
do you have any suggestion for this

thank you very much,
Lynn

**Comment by ThandarLynn** [comment]
It happens when scrolling webview. Teads overlap my webview toolbar.

**Comment by github-benjamin-volland** [comment]
Hello @ThandarLynn ,

you can use the offset feature in the [WebViewHelper](https://github.com/teads/TeadsSDK-android/blob/37046f9c33c0511d3e8d87c2eca6df702beb7f56/TeadsSDKDemo/webviewhelper/src/main/java/tv/teads/webviewhelper/WebViewHelper.kt#L107)

**Comment by ThandarLynn** [comment]
his pls read my message carefully.

My code use android teads with *dynamic* webview url .it's working fine in
last week of april.

from the first week of May,
my code doesn't work again.it's show visibility 0 again.
*your teads code only work for one constant  webview url.*

can you check any code changed in first week of May?

thank you,
Lynn

**Comment by github-benjamin-volland** [comment]
Hello @ThandarLynn,

The visibility is not linked to the webview url. The main reasons to have 0 as visibility is:
- There is an overlay above the view (even if the overlay is transparent)(in this case a warning log is displayed in the logcat)
- The ad view is outside the screen
- The adView is not attached
- The ad view size is less than 80*80px

Best,
