### ISSUE TITLE
android:allowBackup removal

### ISSUE THREAD

**Issue by dpgmedia-gbero** [teads/TeadsSDK-android#221]
Hello,

For some reason it looks like your manifest files contains : `android:allowBackup=true`

Could this be removed ?

Many thanks,

**Comment by github-lucas-bon** [comment]
Hello @dpgmedia-gbero could explain how this property is causing problems for you?
Let me know. Best,

**Comment by dpgmedia-gbero** [comment]
This ends up in our main application manifest. We're then using `tools:replace="allowBackup"` to get rid of it. 
Unless I'm mistaken, I don't think this should have been added by your SDK.

**Comment by github-lucas-bon** [comment]
This is going to be addressed for next release.
