### ISSUE TITLE
TeadsView MediaContainer size

### ISSUE THREAD

**Issue by alexpopa95** [teads/TeadsSDK-android#90]
Hello, we encountered an issue with the media container.
By using `tv.teads.sdk.publisher.TeadsView` the mediacontainer does not fill the entire container.
Using TeadsView.updateSize(View) doesn't change anything.
On iOS platform the view is showing correctly.

**Current:**
<img src="https://cloud.githubusercontent.com/assets/11510670/25535845/c8f6e10c-2c38-11e7-91e8-a6ed028cebd8.png" width="350">

**Expected:**
<img src="https://cloud.githubusercontent.com/assets/11510670/25536089/b7d16c0c-2c39-11e7-9775-3fb0de2508e5.png" width="350">

**XML View**
<tv.teads.sdk.publisher.TeadsView
        android:id="@+id/teads_adview"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal" />

**Temporary fix:**

`View teadsContent = mTeadsView.findViewById(R.id.teads_ad_content);`
`teadsContent.setLayoutParams(new RelativeLayout.LayoutParams(width, height));`

`FrameLayout.LayoutParams flp = new FrameLayout.LayoutParams(width, height);`
`flp.gravity = Gravity.TOP | Gravity.CENTER_HORIZONTAL;`
`mTeadsView.getMediaContainer().getChildAt(0).setLayoutParams(flp);`

`FrameLayout.LayoutParams flp = new FrameLayout.LayoutParams(width, height);`
`flp.gravity = Gravity.TOP | Gravity.CENTER_HORIZONTAL;`
`mTeadsView.getEndScreen().setLayoutParams(flp);`

That fix alteres internal teads-sdk views, so it's not a clean solution for us. Could you apply a fix to show the video container stretched on the entire view?

Thank you for your support!

**Comment by HugoGresse** [comment]
Hi @alexpopa95 
Thanks for reporting this. 

**Two things I've notice**
1. The width/height ratio should be 16:9 for better ad display, that match most of the video we play. 
2. Well, you shouldn't change our layout size from what you expect... 

**Result**
From what I can say, the Android layout does not have any issue, the iOS one have. The video overlay (mute button, progress bar and so one) should match the video size, not the container.
